### ISSUE TITLE
Coloured and Rearranged Output  [Feature Request]

### ISSUE THREAD

**Issue by marcabrus** [kmansouri/OPERA#10]
I like a lot the possibility to have neighbours information within the table output. Since It's just a CSV it is  a little bit difficult to have a nice overview of the results.
Could you consider to add also xls output maybe with a different layout and colour codes?
I tried to do an example table with KNIME,  maybe it could be something useful to understand what I mean.
This is the example on what it could be: 
![image](https://user-images.githubusercontent.com/335108/79475702-54431e80-8008-11ea-96b4-02dbaa197e3e.png)

[OPERA2.3_Pred_CERAPP.xlsx](https://github.com/kmansouri/OPERA/files/4488202/OPERA2.3_Pred_CERAPP.xlsx)

If you want to have a look at the workflow it's here:
[opera output to XLS 50 sample.zip](https://github.com/kmansouri/OPERA/files/4488157/opera.output.to.XLS.50.sample.zip)

**Comment by kmansouri** [comment]
Thanks for the comment. However, for the display, we prefer to keep it as simple as possible. You are welcome to use and color-code your results based on your preferences.
