### ISSUE TITLE
Original Smiles in the output file are wrong

### ISSUE THREAD

**Issue by Sukis123** [kmansouri/OPERA#13]
Dear OPERA developer, 

I am using OPERA 2.6 and I found that the Original Smiles in the output are wrong. I think they are 
Canonical_QSARr because they are exactly the same but different from my original Smiles. As some of my input were incompatible for the prediction, and the number of row in the results is different from that in my input file, the original Smiles is important to correlate my input and the results.

many thanks.

best regards,
Sukis

**Comment by kmansouri** [comment]
Hi Sukis,
Thanks for using OPERA! 
OPERA applies a QSAR-ready standardization process which results in QSAR-ready structures that are used for predictions. So if you prefer to use your original structures exactly as they are without any alteration, then you need to turn off the standardization tool.
I hope this helps. If youd'd like me to take a look at your structures, please send them to me by email.
Best!
