### ISSUE TITLE
OPERA 2.6 command line parallel version crashing

### ISSUE THREAD

**Issue by rvaidya** [kmansouri/OPERA#15]
Hi Kamel,

The command line parallel version of OPERA 2.6 is crashing for an input that works with the normal version:

```
INFO: Adding explicit H false
Aug 22, 2020 6:14:08 AM net.guha.apps.cdkdesc.CDKdescBatch batchDescriptor
INFO: Will evaluate 50 descriptors
Aug 22, 2020 6:14:08 AM net.guha.apps.cdkdesc.CDKdescBatch batchDescriptor
INFO: Got 50 descriptor instances
Exception in thread "main" java.lang.NullPointerException
        at net.guha.apps.cdkdesc.CDKDescUtils.isSMILESFormat(CDKDescUtils.java:74)
        at net.guha.apps.cdkdesc.CDKdescBatch.batchDescriptor(CDKdescBatch.java:227)
        at net.guha.apps.cdkdesc.CDKdesc.main(CDKdesc.java:510)
Aug 22, 2020 6:14:08 AM net.guha.apps.cdkdesc.CDKdescBatch batchDescriptor
INFO: output:   CDKtemp/CDKDesc_8_temp.csv
Aug 22, 2020 6:14:08 AM net.guha.apps.cdkdesc.CDKdescBatch batchDescriptor
INFO: type:     all
Aug 22, 2020 6:14:08 AM net.guha.apps.cdkdesc.CDKdescBatch batchDescriptor

```

From using CDK, I know that it is not thread safe - does it need a lock around CDK functionality?

**Comment by kmansouri** [comment]
Thank you Rahul,

The parallel version is only recommended for 5000 chemicals or more at a time, as mentioned on the releases page. But of course, it'll work within your computational resources. So if you run 50,000 with limited RAM it'll crash. 
The second example does not seem like a crash to me. If you ran one molecule, it seems that the calculation is finished. Some of the descriptors throw exceptions sometimes. If you don't like to see the full output you should use verbose mode "1" minimum or "0" silent. I hope this helps.
