### ISSUE TITLE
CPU usage of PadDEL Java VM

### ISSUE THREAD

**Issue by tsufz** [kmansouri/OPERA#17]
Hi @kmansouri,
IMHO, the CPU usage of the PadDEL JAVA VM is to high to run OPERA in background while doing other stuff. You may consider to run PadDEL with lower priority (below normal) and / or restrict to one CPU core?

See https://superuser.com/questions/620724/changing-windows-process-priority-via-command-line and https://stackoverflow.com/questions/7759948/set-affinity-with-start-affinity-command-on-windows-7 for examples.

Txs and best,
Tobias

**Comment by kmansouri** [comment]
Hi Tobias,

It is true that OPERA development was not really prioritizing running in the background to do other stuff but rather to finish the calculation as fast as possible. But I understand that different users have different priorities and it's not always easy to make everyone happy :) But thanks for the tips! I will take a look and experiment with it for the next version/update.
