### ISSUE TITLE
pka-b value

### ISSUE THREAD

**Issue by tsufz** [kmansouri/OPERA#18]
Hi @kmansouri, 
I have a question the pKa-b value in the output table. It this the base pKa? Unfortunately, this is not documented.

Best wishes,
Tobias

**Comment by kmansouri** [comment]
Hi Tobias, 
OPERA pKa model predicts the strongest acidic (pKa_a) and basic (pKa_b) values.
That is documented in the pKa model publication cited on the repo page.
Please use those references for additional details about the models.

Best
Kamel
