### ISSUE TITLE
Consistency of endpoints

### ISSUE THREAD

**Issue by tsufz** [kmansouri/OPERA#2]
Hi,
The endpoints and their abbreviations in the field headers should be harmonised and well documented. This would be helpful for the automated processing of the output files.

One examples:
AOH: LogOH, but AD_AOH.

The examples are maybe typos, but this part should be revised and harmonsed.

Yours
Tobias

**Comment by kmansouri** [comment]
Thanks Tobias. I will add documentation clarifying the field headers.
BTW,  AD is the applicability domain.

**Comment by tsufz** [comment]
Hi Kamal, I think this was an missunderstanding. There is a typo in the AOH column names. LogOH should read LogAOH to be in line with the other column names and the endpoint. I know that AD is the applicability domain, but thanks for clarification.

Yours,
Tobias

**Comment by kmansouri** [comment]
I see. It wasn't actually a typo as logOH is also commonly used but I agree with you about the consistency.
Thanks for mentioning that!
