### ISSUE TITLE
Silent Installation-mode

### ISSUE THREAD

**Issue by AndreasDie** [kmansouri/OPERA#20]
Hi Kamel,

is it possible to install Opera for windows in a silent way? 
We have some users where we have to install and update it. I tried on my own but it seems the installer is waiting for any feedback when running it with a /s parameter. 

Cheers,
Andreas

**Comment by kmansouri** [comment]
Hi Andreas,

Yes, you can! use the command: OPERA_installer.exe -mode silent -agreeToLicense yes
For more info: https://www.mathworks.com/help/compiler/install-deployed-application.html
Just FYI, the new version 2.7 is now available.

Best!
Kamel
