### ISSUE TITLE
CDK Exception

### ISSUE THREAD

**Issue by cjhousand** [kmansouri/OPERA#21]
The following exception is thrown when processing the attached SDF file.  Using CL version of OPERA.  All outputs are enabled.

Note: file extension changed from .sdf to .txt because GitHub wouldn't let me upload the SDF file for some reason.

=============== Exceptions ===============
441326609 lengthOverBreadth org.openscience.cdk.exception.CDKException: Error in center of mass calculation, has exact mass been set on all atoms?

[ARV-471.txt](https://github.com/kmansouri/OPERA/files/6633413/ARV-471.txt)

**Comment by kmansouri** [comment]
That is simply because the ID of your molecule is numeric. The descriptor calculator was "confused" when assigning the descriptors to a numeric value. Try adding a letter to the name/ID of the molecule and it should work. Let me know if it doesn't.
Also, v 2.7 is out. Thanks!
