### ISSUE TITLE
Melting points for organic molecule with 90 atoms (C & H only)

### ISSUE THREAD

**Issue by kcbhamu** [kmansouri/OPERA#22]
Dear Prof. kmansouri 
I am curious to calculate the melting and boiling point  (M.P. & B.P.) of some organic molecules with 90 atoms (C & H only) keeping the molecular weight less than 2000 g/Mol.

Could you please confirm, whether it can predict accurate M.P. and B.P.  for such a large molecule for which the experimental or any other data are not available in the literature?

Thanks

Regards
Bhamu

**Comment by kmansouri** [comment]
Hi Bhamu,
Thank you for your interest in OPERA. 90 atoms is within the limit and seem feasible. You'll need to try it and take the applicability domain and accuracy estimates provided into consideration. These parameters are case by case and calculated for every prediction.
