### ISSUE TITLE
what is the minimum memory capacity requirements for OPERA calculation？

### ISSUE THREAD

**Issue by biotech7** [kmansouri/OPERA#23]
Hi,
    I deployed a LibOPERA_Py on Centos 7 server with capacity of 1G cpu 2G RAM. during running melting point prediction for one molecule, process terminated/killed accidently by sys.
    so what's the minimum requirements for OPERA model prediction?

>[root@VM-0-9-centos local]# python3
>Python 3.7.0 (default, Aug  9 2021, 15:58:55) 
>[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
>Type "help", "copyright", "credits" or "license" for more information.
> import libOPERA_Py as OPERA
> opera = OPERA.initialize()
>pred = opera.OPERA('--SMI','/usr/local/test.smi','-o','pred.txt','-MP','-v',1)

>Endpoint to be calculated: MP

 >Initializing and loading models...

>============= Molecular Descriptors ============
>Loaded structures: 1.
>PaDEL calculating 2D descriptors...
>PaDEL descriptors calculated for: 1 molecules.
>Loading of PaDEL descriptors file...
>Checking loaded variables.
>Loaded 1444 PaDEL descriptors for 1 molecules.

>============== Running The Models ==============
>Predicting MP values (Deg. C)...
>Killed

**Comment by kmansouri** [comment]
Hi,
Thanks for reporting this. I don't know the exact minimum. It seems that you're using it for only 1 molecule so it should work with what you have. You also have a swap in linux so I'm afraid there is some other issue here. I recommend you do some troubleshooting and make sure nothing else is running at the same time and taking all you 2G of RAM + swap.
Let me know how it goes!
Best
Kamel
