### ISSUE TITLE
Customising of pH for log D calculations

### ISSUE THREAD

**Issue by tsufz** [kmansouri/OPERA#3]
Hi Kamel, It would be great if the used pH could be customised. We require also other than the standard pHs. I suggest something like `opera -s input.sdf -O output.csv -logD7.4 -logD5.0 -x -v 0` or so.

Yours
Tobias

**Comment by kmansouri** [comment]
Hi Tobias, sorry for the delayed answer. OPERA can predict logD values for both pH 5.5 and 7.4.
for anything else, the pH function (approx) can be used based on the pKa and logP predictions.
