### ISSUE TITLE
question about the datasets used for training

### ISSUE THREAD

**Issue by mmagithub** [kmansouri/OPERA#31]
Hello,
For the provided Opera datasets, I am a bit confused about what does the updated files means (for example: LogP_2.9_update.csv), are they additional experimental data used for training the models, in addition to the original sdf files (ends by QR), or they are estimates from the predictions, especially the provided activity values in these updates are given as 'value_point_estimate',

Thanks,
Marawan

**Comment by kmansouri** [comment]
Hi, thank you for using OPERA and for reaching out. Those are additional datasets. Point estimates are experimental values.

**Comment by mmagithub** [comment]
Thanks, one more question, for some datasets it is not quiet clear where is the experimental datafield in the provided csv files, for example, in the Caco2_QR.csv, I can only find 'CalculatedLogPapp' which the file lacks the experimental endpoint, am I missing something here ?
