### ISSUE TITLE
Java installation is required?

### ISSUE THREAD

**Issue by JenniferHem** [kmansouri/OPERA#33]
Hi @kmansouri 

I just tried using OPERA 2.9 and encountered the error which says: "Command java not found". Does OPERA require an additional JAVA installation? If so, are there any requirements on the Version? (Sorry I cannot upload a screenshot, somehow my upload is blocked)

Thanks in advance for the answer!

**Comment by JenniferHem** [comment]
P.S: I installed OpenJDK 17 and after that it works. Would be great to add a section in the installation Manual about Java requirements.

**Comment by kmansouri** [comment]
Hi, Thank you for using OPERA. Yes Java is required and is actually already mentioned in the "Tool requirements" section right on top of the the section from which you downloaded the installer.
