### ISSUE TITLE
Experimental results in Caco2_QR.csv

### ISSUE THREAD

**Issue by mmagithub** [kmansouri/OPERA#35]
Hi,
For some datasets it is not quiet clear where is the experimental data field in the provided csv files, for example, in the Caco2_QR.csv, I can only find 'CalculatedLogPapp' which the file lacks the experimental endpoint, am I missing something here ?

**Comment by kmansouri** [comment]
you're right that the "CalculatedLogPapp" column is not clear. It is the experimental value but it was converted because it was in different units. We will change that in the next update. Thanks
