### ISSUE TITLE
Problem generating padel descriptors

### ISSUE THREAD

**Issue by PARODBE** [kmansouri/OPERA#37]
Hi,

thank you for so useful library. One question, why sometimes I obtain the error of that padel descriptors for some compounds have not been generated? And in other situations, I obtain NaNs in pka, why?

**Comment by kmansouri** [comment]
Thank you for using OPERA. The tool does not work for certain chemicals (inorganics, mixtures, nano-chemicals, UVCBs, markush...). You need to use the standardization tool to avoid that issue. 
For pKa, not all chemicals are ionizable. And some only have acidic or basic pKa, not both.
Please take a look at the OPERA paper and the pKa paper mentioned on the main page for more info. Thanks
