### ISSUE TITLE
Error with path in OPERA2_linux.m

### ISSUE THREAD

**Issue by mc-robinson** [kmansouri/OPERA#4]
Using the newest offline installation for linux, I ran into the following issue:

```
PaDEL calculating 2D descriptors...
Error: Unable to access jarfile /usr/local/bin/OPERA/papplication/adel-full-1.00.jar
End of descriptors calculation: Undefined function or variable 'linux'.
```

Digging into the source code a bit, I believe the problematic line is 419 in OPERA2_linux.m, where the file path is indeed specified as above. 

Obviously this seems to just be an error with the placement of the p. However, I do believe there is another issue with the file. Upon installation, one can choose to install somewhere other than `/usr/local/bin/`, as I did. However, the path seems to be unchanged in this file. I can't test this with this installation since I can only find the executable, but this may be an issue.

Thanks,
Matt

**Comment by kmansouri** [comment]
Thank you for using OPERA and sorry for the delay in answering this. The application is now more flexible with the installation location and can adapt to that.
