### ISSUE TITLE
does opera GUI perform de novo estimates?

### ISSUE THREAD

**Issue by cbroeckl** [kmansouri/OPERA#41]
I am interested in using OPERA to estimate physicochemical parameters - specifically pKa.   I downloaded the GUI and it seems that i only get pKa values returned which are already in the CompTox dashboard - i.e. when the strucuture matches an existing structure, i see the results, else it reports that the compound is not in the database.  Is it possible to get de-novo predictions out for compounds NOT currently in the ComTox database?    Thanks.

**Comment by kmansouri** [comment]
Thank you for using OPERA. What do you mean by "seems that i only get pKa values returned which are already in the CompTox dashboard"? What is the input you're using? Have you tried the sample files and checked the help/guide to get clarification on how the tool works?

**Comment by kmansouri** [comment]
I'm about to close this issue for inactivity. 
If you use a text file (.txt) with identifiers such as CAS or DTXSID, OPERA will identify it and use the right structure (if it's in OPERA's knowledge base from EPA DSSToX). 
If you want to predict chemical structures you need to provide it in a structure format (.smi, .sdf, .mol).
See the provided sample input files for reference.
