### ISSUE TITLE
problem with starting app.

### ISSUE THREAD

**Issue by Mikusumoto** [kmansouri/OPERA#43]
When I start OPERA_UI/CL, the app crashed/no command line displayed.
There were no problem when I installed softwares.
Please tell me how to do solution.

**Comment by kmansouri** [comment]
was that one time or every time you start it? Can you provide more information?

**Comment by Mikusumoto** [comment]
I appreciate your response.
Actually, I've already solved this problem by using compatibility mode(start app by not windows 10 but 8).
Thank you for your cooperation.

Best regards,
