### ISSUE TITLE
Opera 2.1 for Windows 32 bit

### ISSUE THREAD

**Issue by jcgraham** [kmansouri/OPERA#5]
Hi,
   I am trying to run Collaborative Acute Toxicity Modeling Suite (CATMoS), a free resource for screening organic chemicals for acute oral toxicity. It is implemented in v2.0 of OPERA.  The NIEHS site directs here https://github.com/NIEHS/OPERA/releases/tag/v2.1-beta3.-windows, but these versions say they are incompatible with my computer (32 bit).  Is there an available version for 32-bit windows?
Thank you, Jessica

**Comment by kmansouri** [comment]
Sorry for the delayed answer, unfortunately, we only have 64bits versions. The application performs a number of calculations that are more appropriate for 64bits machines.
