### ISSUE TITLE
Java 8 dependency of PaDEL

### ISSUE THREAD

**Issue by tsufz** [kmansouri/OPERA#9]
Hi Kamal,
In enterprise environments, Java is not free anymore. Either the company pays for the runtime JRE or they switch to use OpenJDK. I would like to ask to shift to support also OpenJDK if possible.

Thanks and best wishes,
Tobias

**Comment by tsufz** [comment]
Hi, I was too lazy. I suggest to add an advice to change to an open license, e.g.
Download latest OpenJDK from https://jdk.java.net/13/ unzip for example to `c:/java/java13/jdk-13.0.1` and add the path to the folder with the binary `c:\java\java13\jdk-13.0.1\bin` to the `%path% variable`(for example: https://javatutorial.net/set-java-home-windows-10.

**Comment by kmansouri** [comment]
Thanks Tobias! Good suggestion

**Comment by tsufz** [comment]
We use https://adoptopenjdk.net/ now. Good way to get rid of manual setting adjustment.
